[package]
distribution = "2201.10.0"
org = "xlibb"
name = "sikulix"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/xlibb/module-sikulix"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib.sikulix"
artifactId = "sikulix-native"
version = "0.1.0"
path = "../native/build/libs/sikulix-native-0.1.0-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "com.sikulix"
artifactId = "sikulixapi"
version = "2.0.5"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "org.python"
artifactId = "jython-slim"
version = "2.7.2"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.antlr"
artifactId = "antlr"
version = "3.5.2"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.antlr"
artifactId = "ST4"
version = "4.0.8"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "javax.servlet"
artifactId = "javax.servlet-api"
version = "3.1.0"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.antlr"
artifactId = "antlr-runtime"
version = "3.5.2"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-compress"
version = "1.19"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "1.62"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "1.62"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm"
version = "7.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm-commons"
version = "7.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm-tree"
version = "7.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm-analysis"
version = "7.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.ow2.asm"
artifactId = "asm-util"
version = "7.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "28.0-android"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.google.guava"
artifactId = "listenablefuture"
version = "9999.0-empty-to-avoid-conflict-with-guava"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.google.code.findbugs"
artifactId = "jsr305"
version = "3.0.2"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.checkerframework"
artifactId = "checker-compat-qual"
version = "2.5.5"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.google.errorprone"
artifactId = "error_prone_annotations"
version = "2.3.2"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.google.j2objc"
artifactId = "j2objc-annotations"
version = "1.3"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.codehaus.mojo"
artifactId = "animal-sniffer-annotations"
version = "1.17"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.google.guava"
artifactId = "failureaccess"
version = "1.0.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.ibm.icu"
artifactId = "icu4j"
version = "59.1"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.carrotsearch"
artifactId = "java-sizeof"
version = "0.0.5"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jffi"
version = "1.2.20"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jnr-netdb"
version = "1.1.6"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jnr-ffi"
version = "2.1.10"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jffi"
version = "1.2.19"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jnr-a64asm"
version = "1.0.0"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jnr-x86asm"
version = "1.0.2"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jnr-posix"
version = "3.0.50"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "com.github.jnr"
artifactId = "jnr-constants"
version = "0.9.12"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "jline"
artifactId = "jline"
version = "2.14.5"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.45.Final"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.45.Final"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.45.Final"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.45.Final"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.45.Final"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.45.Final"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.apache.ant"
artifactId = "ant"
version = "1.9.7"

# transitive dependency of org.python:jython-slim:2.7.2
[[platform.java17.dependency]]
groupId = "org.apache.ant"
artifactId = "ant-launcher"
version = "1.9.7"

# # transitive dependency of com.sikulix:sikulixapi:2.0.5
# [[platform.java17.dependency]]
# groupId = "org.jruby"
# artifactId = "jruby-complete"
# version = "9.2.11.1"

# # transitive dependency of com.sikulix:sikulixapi:2.0.5
# [[platform.java17.dependency]]
# groupId = "com.sikulix"
# artifactId = "sikulix2tigervnc"
# version = "1.1.4"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "org.openpnp"
artifactId = "opencv"
version = "4.3.0-3"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "commons-cli"
artifactId = "commons-cli"
version = "1.4"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-exec"
version = "1.3"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "net.java.dev.jna"
artifactId = "jna-platform"
version = "5.6.0"

# transitive dependency of net.java.dev.jna:jna-platform:5.6.0
[[platform.java17.dependency]]
groupId = "net.java.dev.jna"
artifactId = "jna"
version = "5.6.0"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "net.oneandone.reflections8"
artifactId = "reflections8"
version = "0.11.6"

# transitive dependency of net.oneandone.reflections8:reflections8:0.11.6
[[platform.java17.dependency]]
groupId = "org.javassist"
artifactId = "javassist"
version = "3.22.0-GA"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "net.sourceforge.tess4j"
artifactId = "tess4j"
version = "4.5.4"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "com.github.jai-imageio"
artifactId = "jai-imageio-core"
version = "1.4.0"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.ghost4j"
artifactId = "ghost4j"
version = "1.0.1"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "log4j"
artifactId = "log4j"
version = "1.2.17"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "commons-beanutils"
artifactId = "commons-beanutils"
version = "1.9.2"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "commons-collections"
artifactId = "commons-collections"
version = "3.2.1"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.apache.xmlgraphics"
artifactId = "xmlgraphics-commons"
version = "1.4"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "com.lowagie"
artifactId = "itext"
version = "2.1.7"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox"
version = "2.0.21"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "fontbox"
version = "2.0.21"

# # transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
# [[platform.java17.dependency]]
# groupId = "commons-logging"
# artifactId = "commons-logging"
# version = "1.2"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox-tools"
version = "2.0.21"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "pdfbox-debugger"
version = "2.0.21"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.apache.pdfbox"
artifactId = "jbig2-imageio"
version = "3.0.3"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.8.0"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "net.sourceforge.lept4j"
artifactId = "lept4j"
version = "1.13.2"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.jboss"
artifactId = "jboss-vfs"
version = "3.2.15.Final"

# transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
[[platform.java17.dependency]]
groupId = "org.jboss.logging"
artifactId = "jboss-logging"
version = "3.1.4.GA"

# # transitive dependency of net.sourceforge.tess4j:tess4j:4.5.4
# [[platform.java17.dependency]]
# groupId = "org.slf4j"
# artifactId = "slf4j-api"
# version = "1.7.30"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-nop"
version = "1.7.28"

# transitive dependency of com.sikulix:sikulixapi:2.0.5
[[platform.java17.dependency]]
groupId = "net.sf.py4j"
artifactId = "py4j"
version = "0.10.9.1"

